SELECT ABS(-10) FROM dual;

SELECT CEIL(5.25) FROM dual;

SELECT FLOOR(5.75) FROM dual;

SELECT ROUND(5.257, 2) FROM dual;

SELECT TRUNC(5.257, 2) FROM dual;

SELECT SQRT(25) FROM dual;

SELECT POWER(2, 3) FROM dual;

SELECT EXP(2) FROM dual;